Docker installation complete

diff --git a/scripts/subscripts/install-docker b/scripts/subscripts/install-docker
--- a/scripts/subscripts/install-docker
+++ b/scripts/subscripts/install-docker
@@ -1,3 +1,31 @@
 #! /bin/bash
+set -euo pipefail
+export DEBIAN_FRONTEND=noninteractive
+trap 'echo "Installation failed on line $LINENO"' ERR
 
-echo 'installing docker'
+echo "--------------------------"
+echo "Starting with docker installation ..."
+
+echo "- Removing conflicting packages"
+sudo apt remove -y docker.io docker-compose docker-compose-v2 docker-doc podman-docker containerd runc || true
+
+echo "- Add Docker's official GPG key"
+sudo apt update
+sudo apt install -y ca-certificates curl
+sudo install -m 0755 -d /etc/apt/keyrings
+sudo curl -fsSL https://download.docker.com/linux/ubuntu/gpg -o /etc/apt/keyrings/docker.asc
+sudo chmod a+r /etc/apt/keyrings/docker.asc
+
+echo "- Add the repository to Apt sources"
+sudo tee /etc/apt/sources.list.d/docker.sources <<EOF
+Types: deb
+URIs: https://download.docker.com/linux/ubuntu
+Suites: $(. /etc/os-release && echo "${UBUNTU_CODENAME:-$VERSION_CODENAME}")
+Components: stable
+Signed-By: /etc/apt/keyrings/docker.asc
+EOF
+
+sudo apt update
+
+echo "- Install latest docker version"
+sudo apt install -y docker-ce docker-ce-cli containerd.io docker-buildx-plugin docker-compose-plugin
